const products = [
    {
        _id: '1',
        name :'airpords wireless ',
        image: '/images/airpods.jpg',
        description: 'Bluetootht dsflkhdhs qjfbq qdbfae  qdbfqlef qeoqjfijaifq baif  fqifbjaj qbdqdiaa fqeio',
        brand: 'apple' ,
        category: 'electronique',
        price: 88.99,
        countInStock: 3,
        rating: 4.5,
        numReviews:4,
    },
    {
        _id: '2',
        name :'airpords wireless ',
        image: '/images/alexa.jpg',
        description: 'Bluetootht dsflkhdhs qjfbq qdbfae  qdbfqlef qeoqjfijaifq baif  fqifbjaj qbdqdiaa fqeio',
        brand: 'apple' ,
        category: 'electronique',
        price: 88.99,
        countInStock: 3,
        rating: 4.5,
        numReviews:4,
    },
    {
        _id: '3',
        name :'airpords wireless ',
        image: '/images/camera.jpg',
        description: 'Bluetootht dsflkhdhs qjfbq qdbfae  qdbfqlef qeoqjfijaifq baif  fqifbjaj qbdqdiaa fqeio',
        brand: 'apple' ,
        category: 'electronique',
        price: 88.99,
        countInStock: 3,
        rating: 4.5,
        numReviews:4,
    },
    {
        _id: '4',
        name :'airpords wireless ',
        image: '/images/mouse.jpg',
        description: 'Bluetootht dsflkhdhs qjfbq qdbfae  qdbfqlef qeoqjfijaifq baif  fqifbjaj qbdqdiaa fqeio',
        brand: 'apple' ,
        category: 'electronique',
        price: 88.99,
        countInStock: 3,
        rating: 4.5,
        numReviews:4,
    },
    {
        _id: '5',
        name :'airpords wireless ',
        image: '/images/phone.jpg',
        description: 'Bluetootht dsflkhdhs qjfbq qdbfae  qdbfqlef qeoqjfijaifq baif  fqifbjaj qbdqdiaa fqeio',
        brand: 'apple' ,
        category: 'electronique',
        price: 88.99,
        countInStock: 3,
        rating: 4.5,
        numReviews:4,
    },
    {
        _id: '6',
        name :'airpords wireless ',
        image: '/images/playstation.jpg',
        description: 'Bluetootht dsflkhdhs qjfbq qdbfae  qdbfqlef qeoqjfijaifq baif  fqifbjaj qbdqdiaa fqeio',
        brand: 'apple' ,
        category: 'electronique',
        price: 88.99,
        countInStock: 3,
        rating: 4.5,
        numReviews:4,
    },
]

export default products